import type { Code } from 'mdast';
import type { ExtractContext } from '../markdown/context.js';
import { buildLineMap } from '../markdown/lineMap.js';
import { endOf, startOf } from '../markdown/parse.js';
import { findComments, findDocstrings, parsesAsCode, type CommentRange } from './parsers.js';

interface Line {
  bodyStart: number;
  bodyEnd: number;
  indent: number;
  /** Absolute column of the body in its line. */
  col: number;
}

interface CommentShape {
  lines: Line[];
  closer?: string;
}

const LINE_MARKER = /^(?:\/\/[/!]?|#+(?!>)|--+|;+|'|%+|REM\b|rem\b|::)/;
const BLOCK_OPENERS: [RegExp, string][] = [
  [/^\/\*[*!]?/, '*/'],
  [/^<!--/, '-->'],
  [/^<#/, '#>'],
  [/^\{-/, '-}'],
  [/^--\[=*\[/, ']]'],
  [/^=begin\b/, '=end'],
  [/^[rRuUbB]{0,2}"""/, '"""'],
  [/^[rRuUbB]{0,2}'''/, "'''"],
];

const DIRECTIVE =
  /^(?:eslint|prettier-ignore|@ts-|tslint:|jshint|jscs:|global\s|istanbul\s|c8\s|v8\s|noqa|type:\s|pylint:|mypy:|pyright:|fmt:|isort:|nolint|nosec|NOSONAR|#?region\b|#?endregion\b|pragma\b|ReSharper\b|cSpell|spell-?checker|webpackChunkName|@vite-ignore|<reference\b|-\*-|vim:|shellcheck\b|nuget:|#!|@flow\b|@jsx\b|biome-ignore|deno-lint|swiftlint|rubocop:|clang-format|NOLINT|@formatter:|@generated\b|SPDX-License-Identifier|Copyright\b|\(c\)\s|©|Licensed under\b|All rights reserved|<auto-generated|codegen|@refresh|@jest-environment|@vitest-environment|language=|requires\s|#requires|using namespace)/i;

const TAG_PREFIX =
  /^(?:@(?:param|arg|argument|prop|property|typeparam|template|throws|exception|callback|typedef|type|field|member|var)\b(?:\s*\{[^}]*\})?(?:\s+(?:\[[^\]]*\]|[\w$.]+))?(?:\s+-\s+|\s+|$)|@\w+(?:\s*\{[^}]*\})?(?:\s+-\s+|\s+|$)|:(?:param|type|raises|rtype|returns?|var|ivar|cvar)\b[^:]*:\s*|\\(?:param|tparam|throws|return|returns|brief|details|note)\b(?:\[[^\]]*\])?(?:\s+\w+)?\s*)/;

const MARKER_PREFIX = /^(?:TODO|FIXME|HACK|XXX|NOTE|BUG|WARNING|WARN|IMPORTANT|REVIEW|OPTIMIZE|DEPRECATED|SAFETY|NB)(?:\([^)]*\))?:?\s+/;

// Docstring conventions that documentation tools parse (Sphinx/Napoleon, NumPy); they must stay verbatim.
const DOC_SECTION = /^(?:Args|Arguments|Parameters|Params|Other Parameters|Keyword Args|Keyword Arguments|Kwargs|Returns?|Yields?|Raises|Raise|Except(?:ions)?|Warns|Warnings?|See Also|Notes?|References|Examples?|Attributes|Methods|Todo)\s*:?\s*$/;
const DOC_UNDERLINE = /^[-=~^]{3,}\s*$/;
const DOC_ENTRY_SECTIONS = /^(?:Args|Arguments|Parameters|Params|Other Parameters|Keyword Args|Keyword Arguments|Kwargs|Returns?|Yields?|Raises|Raise|Except(?:ions)?|Warns|Attributes|Methods)$/;
/** Google entry `name (type): ` / `Type: ` or NumPy entry `name : type` (whole line). */
const GOOGLE_ENTRY = /^\*{0,2}[A-Za-z_][\w.]*(?:\s*\([^)]*\))?:\s+/;
const NUMPY_ENTRY = /^\*{0,2}[A-Za-z_]\w*(?:\s*,\s*\*{0,2}[A-Za-z_]\w*)*\s+:\s+\S.*$/;
/** A bare type line such as `bool`, `list[str]` or `int or None` (NumPy Returns/Yields). */
const TYPE_LINE = /^[A-Za-z_][\w.]*(?:\[[^\]]*\])?(?:\s*(?:\||,|\bor\b)\s*[A-Za-z_][\w.]*(?:\[[^\]]*\])?)*$/;
const RST_DIRECTIVE = /^\.\.\s+[\w-]+::\s*/;

/** Spans inside comment text that are code, not prose. */
const COMMENT_CODE_SPANS = [
  /``[^`\n]+``/g,
  /`[^`\n]+`/g,
  /<(c|code|see|seealso|paramref|typeparamref|langword)\b[^>]*>[\s\S]*?<\/\1>/g,
  /<\/?[A-Za-z][\w:.-]*(?:\s[^<>]*)?\/?>/g,
  /\{@\w+[^}]*\}/g,
  /\[`[^`\]]+`\]|\[\w+(?:::|\.)[\w.:]+\]/g,
];

function looksLikeCode(text: string): boolean {
  const s = text.trim();
  if (!s) return false;
  if (/^(?:import|from|export|return|if|else|elif|for|foreach|while|switch|case|var|let|const|def|class|function|func|fn|public|private|protected|static|using|namespace|package|#include|#define|try|catch|throw|await|yield|echo|cd|ls|rm|cp|mv|mkdir|sudo|npm|npx|pip|dotnet|git|docker|kubectl|az|curl|wget|param|select|insert|update|delete|create|alter|drop|print|console\.log|resource|module|output|targetScope)\b/i.test(s) &&
    /[=(){}[\];$<>]|\s--?\w/.test(s) && !/[.!?:]$/.test(s)) return true;
  if (/[;{}]$/.test(s)) return true;
  if (/^[\w$.[\]'"]+\s*(?:[+\-*/%|&]?=|=>|:=|<-)\s*\S/.test(s) && !/\s(?:is|are|the|a|an|to|of)\s/i.test(s)) return true;
  if (/^[\w$.]+\(.*\)[;,]?$/.test(s)) return true;
  if (/^<\/?[A-Za-z][^>]*>$/.test(s)) return true;
  const sym = (s.match(/[{}()[\];=<>$|&]/g) ?? []).length;
  return sym / s.length > 0.15;
}

/**
 * Commented-out code detection. With a grammar for the language, text the grammar rejects is prose;
 * text it accepts is code when the heuristics agree or it carries a strong code signal.
 */
export function isCode(lang: string, text: string): boolean {
  const s = text.trim();
  if (!s) return false;
  const heuristic = looksLikeCode(s);
  const valid = parsesAsCode(lang, s);
  if (valid === null) return heuristic;
  if (!valid) return false;
  return heuristic || (/[(){}[\];=]|=>|::|->/.test(s) && !/[.!?]$/.test(s));
}

function shape(code: string, c: CommentRange): CommentShape | null {
  const text = code.slice(c.start, c.end);
  for (const [re, closer] of BLOCK_OPENERS) {
    const open = re.exec(text);
    if (!open || !text.endsWith(closer)) continue;
    const innerStart = c.start + open[0].length;
    const innerEnd = c.end - closer.length;
    if (innerEnd < innerStart) return null;
    const lines: Line[] = [];
    let pos = innerStart;
    const cStyle = closer === '*/';
    while (pos <= innerEnd) {
      let nl = code.indexOf('\n', pos);
      if (nl === -1 || nl > innerEnd) nl = innerEnd;
      const lineText = code.slice(pos, nl);
      const deco = (lines.length === 0 ? /^[ \t]*/ : cStyle ? /^[ \t]*(?:\*(?!\/)[ \t]?)?/ : /^[ \t]*/).exec(lineText)![0];
      const extra = /^[ \t]*/.exec(lineText.slice(deco.length))![0].length;
      const bodyStart = pos + deco.length + extra;
      const bodyEnd = pos + lineText.replace(/[ \t\r]+$/, '').length;
      lines.push({ bodyStart, bodyEnd: Math.max(bodyStart, bodyEnd), indent: extra, col: bodyStart - (code.lastIndexOf('\n', bodyStart - 1) + 1) });
      if (nl >= innerEnd) break;
      pos = nl + 1;
    }
    return { lines, closer };
  }
  const marker = LINE_MARKER.exec(text);
  if (!marker || text.includes('\n')) return null;
  const rest = text.slice(marker[0].length);
  const lead = /^[ \t]*/.exec(rest)![0].length;
  const bodyStart = c.start + marker[0].length + lead;
  const bodyEnd = c.start + text.replace(/[ \t\r]+$/, '').length;
  return { lines: [{ bodyStart, bodyEnd: Math.max(bodyStart, bodyEnd), indent: Math.max(0, lead - 1), col: bodyStart - (code.lastIndexOf('\n', bodyStart - 1) + 1) }] };
}

/** Consecutive line comments with the same marker at the same column form one logical comment. */
function groupLineComments(code: string, comments: CommentRange[]): CommentRange[][] {
  const groups: CommentRange[][] = [];
  for (const c of comments) {
    const g = groups[groups.length - 1];
    const prev = g?.[g.length - 1];
    if (prev) {
      const between = code.slice(prev.end, c.start);
      const prevText = code.slice(prev.start, prev.end);
      const curText = code.slice(c.start, c.end);
      const pm = LINE_MARKER.exec(prevText)?.[0];
      const cm = LINE_MARKER.exec(curText)?.[0];
      const col = (o: number) => o - (code.lastIndexOf('\n', o - 1) + 1);
      const isLine = (t: string) => !BLOCK_OPENERS.some(([re]) => re.test(t));
      const standalone = (t: string) => /^#!/.test(t) || DIRECTIVE.test(t.replace(LINE_MARKER, '').trim());
      if (
        /^\r?\n[ \t]*$/.test(between) && pm && pm === cm && isLine(prevText) && isLine(curText) && !standalone(prevText) && !standalone(curText) &&
        col(prev.start) === col(c.start) && isOwnLine(code, prev.start)
      ) {
        g.push(c);
        continue;
      }
    }
    groups.push([c]);
  }
  return groups;
}

function isOwnLine(code: string, offset: number): boolean {
  return /^[ \t]*$/.test(code.slice(code.lastIndexOf('\n', offset - 1) + 1, offset));
}

export function processCodeBlock(ctx: ExtractContext, node: Code) {
  const src = ctx.source;
  const s = startOf(node);
  const e = endOf(node);
  if (!/^[ \t]*(?:`{3,}|~{3,})/.test(src.slice(s, e)) || !node.value) return;
  const lang = node.lang ?? '';
  if (!lang) return;
  const value = node.value;
  const found = findComments(lang, value);
  if (found === null) {
    ctx.notes.push(`code block "${lang}" left untouched (no comment parser for this language)`);
    return;
  }
  const docstrings = findDocstrings(lang, value);
  const withDocstrings = ctx.options.docstrings !== false;
  if (docstrings.length && !withDocstrings) ctx.notes.push(`${docstrings.length} docstring(s) in "${lang}" code left untranslated (docstrings disabled)`);
  const docstringStarts = new Set(withDocstrings ? docstrings.map((d) => d.start) : []);
  const comments = [...found, ...(withDocstrings ? docstrings : [])].sort((a, b) => a.start - b.start);
  if (!comments.length) return;
  const fenceLineEnd = src.indexOf('\n', s);
  if (fenceLineEnd === -1) return;
  const map = buildLineMap(src, fenceLineEnd + 1, value);
  if (!map) {
    ctx.notes.push(`code block "${lang}" left untouched (could not map lines to source)`);
    return;
  }

  for (const group of groupLineComments(value, comments)) {
    const shapes = group.map((c) => shape(value, c));
    if (shapes.some((x) => !x)) continue;
    const lines = shapes.flatMap((x) => x!.lines);
    const closer = shapes[0]!.closer;
    const firstText = value.slice(group[0].start, lines[0].bodyEnd).trim();
    if (DIRECTIVE.test(value.slice(lines[0].bodyStart, lines[0].bodyEnd)) || /^#!/.test(firstText)) continue;
    let inExample = false;
    const docstring = docstringStarts.has(group[0].start);
    for (const para of paragraphs(value, lines, lang, docstring)) {
      const text = para.lines.map((l) => value.slice(l.bodyStart, l.bodyEnd)).join(' ');
      if (/^@example\b/.test(text)) inExample = true;
      else if (/^@\w/.test(text)) inExample = false;
      if (inExample || para.keep || DIRECTIVE.test(text) || /^(?:>>>|\.\.\.)(?:\s|$)/.test(text) || isCode(lang, text)) continue;
      commentSegment(ctx, value, map, para.lines, lang, closer, docstring, para.entry);
    }
  }
}

interface Paragraph {
  lines: Line[];
  /** Structure that must stay verbatim (docstring section header, underline, NumPy entry, doctest or literal block). */
  keep?: boolean;
  /** Inside an Args/Returns/Raises section: the entry prefix (`name (type):`) is protected. */
  entry?: boolean;
}

function paragraphs(value: string, lines: Line[], lang: string, docstring = false): Paragraph[] {
  const out: Paragraph[] = [];
  let cur: Line[] = [];
  let section = '';
  let sectionIndent = -1;
  let numpy = false;
  let prevHeader = false;
  // Docstrings: `>>>` doctest blocks (with their output) and reST literal blocks after `::` stay verbatim.
  let keepCur = false;
  let doctest = false;
  let literal = -1;
  const flush = (keep = false) => {
    if (cur.length) {
      out.push({ lines: cur, keep: keep || keepCur, entry: docstring && DOC_ENTRY_SECTIONS.test(section) });
      const last = cur[cur.length - 1];
      if (docstring && !keepCur && /::$/.test(value.slice(last.bodyStart, last.bodyEnd).trimEnd())) literal = cur[0].col;
    }
    cur = [];
    keepCur = false;
  };
  for (const l of lines) {
    const body = value.slice(l.bodyStart, l.bodyEnd);
    if (!body.trim()) {
      flush();
      doctest = false;
      continue;
    }
    if (docstring) {
      if (literal >= 0) {
        if (l.col > literal) {
          if (!keepCur) {
            flush();
            keepCur = true;
          }
          cur.push(l);
          continue;
        }
        literal = -1;
      }
      if (/^>>>(?:\s|$)/.test(body.trim())) {
        if (!doctest) flush();
        keepCur = doctest = true;
        cur.push(l);
        continue;
      }
      if (doctest) {
        cur.push(l);
        continue;
      }
      const header = DOC_SECTION.exec(body.trim());
      if (header || DOC_UNDERLINE.test(body)) {
        flush();
        if (header) {
          section = body.trim().replace(/\s*:$/, '');
          sectionIndent = l.col;
          numpy = false;
        } else if (prevHeader) numpy = true;
        prevHeader = !!header;
        cur.push(l);
        flush(true);
        continue;
      }
      prevHeader = false;
      // Google style: a line back at the header's indentation ends the section (NumPy sections run to the next header).
      if (section && !numpy && l.col <= sectionIndent) section = '';
      const inEntries = DOC_ENTRY_SECTIONS.test(section);
      if (inEntries && (NUMPY_ENTRY.test(body.trim()) || (numpy && TYPE_LINE.test(body.trim())))) {
        flush();
        cur.push(l);
        flush(true);
        continue;
      }
      if (inEntries && GOOGLE_ENTRY.test(body) && cur.length) flush();
    }
    const code = isCode(lang, body);
    // Lines that are only a doc tag (<summary>, </remarks>) delimit paragraphs.
    const tagOnly = /^<\/?[A-Za-z][^>]*>$/.test(body.trim());
    const startsBlock = /^(?:@\w|[-*+•]\s|\d+[.)]\s|\||>|:\w+.*:|\\\w|```|~~~|<\w|\.\.\s)/.test(body) || code || tagOnly;
    if (startsBlock || (cur.length && Math.abs(l.indent - cur[0].indent) >= 2)) flush();
    cur.push(l);
    if (code || tagOnly) flush();
  }
  flush();
  return out;
}

function commentSegment(ctx: ExtractContext, value: string, map: (v: number) => number, para: Line[], lang: string, closer?: string, docstring = false, entry = false) {
  const src = ctx.source;
  const from = map(para[0].bodyStart);
  const to = map(para[para.length - 1].bodyEnd);
  const mb = ctx.builder();
  para.forEach((l, i) => {
    if (i > 0) mb.text(' ');
    let body = value.slice(l.bodyStart, l.bodyEnd);
    if (i === 0) {
      const tag = TAG_PREFIX.exec(body) ?? (docstring ? RST_DIRECTIVE.exec(body) ?? (entry ? GOOGLE_ENTRY.exec(body) : null) : null) ?? MARKER_PREFIX.exec(body);
      if (tag && tag[0]) {
        mb.placeholder(tag[0], tag[0]);
        body = body.slice(tag[0].length);
      }
    }
    // reST: a trailing `::` introduces the literal block that follows and must survive translation.
    const literalMarker = docstring && i === para.length - 1 && body.endsWith('::');
    if (literalMarker) body = body.slice(0, -2);
    maskComment(mb, body);
    if (literalMarker) mb.placeholder('::', '::');
  });
  let wrap;
  if (para.length > 1) {
    const joiner = src.slice(map(para[0].bodyEnd), map(para[1].bodyStart));
    const eolMatch = /\r?\n/.exec(joiner);
    if (eolMatch) {
      const widths = para.map((l) => map(l.bodyEnd) - (src.lastIndexOf('\n', map(l.bodyEnd) - 1) + 1));
      wrap = {
        width: Math.max(...widths, 40),
        firstColumn: from - (src.lastIndexOf('\n', from - 1) + 1),
        prefix: joiner.slice(eolMatch.index + eolMatch[0].length),
        eol: eolMatch[0],
      };
    }
  }
  const forbidden = closer ? [closer] : [];
  if (closer === '-->') forbidden.push('--');
  // Backslashes would start escape sequences inside a (non-raw) Python string.
  if (docstring) forbidden.push('\\');
  const seg = ctx.segment(mb, {
    kind: 'comment',
    textContext: 'comment',
    original: src.slice(from, to),
    note: docstring ? `${lang} docstring` : `${lang} source code comment`,
    wrap,
    forbidden,
  });
  if (seg) ctx.replace(from, to, seg);
}

function maskComment(mb: ReturnType<ExtractContext['builder']>, body: string) {
  const spans: { start: number; end: number }[] = [];
  for (const re of COMMENT_CODE_SPANS) {
    re.lastIndex = 0;
    for (const m of body.matchAll(re)) spans.push({ start: m.index!, end: m.index! + m[0].length });
  }
  spans.sort((a, b) => a.start - b.start || b.end - a.end);
  let pos = 0;
  for (const sp of spans) {
    if (sp.start < pos) continue;
    mb.source(body.slice(pos, sp.start), 'none');
    mb.placeholder(body.slice(sp.start, sp.end), body.slice(sp.start, sp.end));
    pos = sp.end;
  }
  mb.source(body.slice(pos), 'none');
}
