//! Comments and docstrings in fenced code blocks become segments. Port of `code/comments.ts`.

use super::parsers::{find_comments, find_docstrings, parses_as_code, CommentRange};
use crate::jsstr;
use crate::markdown::context::{ExtractContext, SegmentOptions};
use crate::markdown::line_map::{column_u16, LineMap};
use crate::mask::masking::{EscapeMode, MaskBuilder};
use crate::regexutil::RegexExt;
use crate::rx;
use crate::types::{Render, SegmentKind, TextContext, WrapSpec};

#[derive(Clone, Copy, Debug)]
struct Line {
    body_start: usize,
    body_end: usize,
    indent: usize,
    /// Column of the body in its line (UTF-16 code units).
    col: usize,
}

struct CommentShape {
    lines: Vec<Line>,
    closer: Option<&'static str>,
}

rx!(LINE_MARKER, r"^(?:\/\/[/!]?|#+(?!>)|--+|;+|'|%+|REM\b|rem\b|::)");
rx!(OPEN_C, r"^\/\*[*!]?");
rx!(OPEN_HTML, r"^<!--");
rx!(OPEN_PS, r"^<#");
rx!(OPEN_HS, r"^\{-");
rx!(OPEN_LUA, r"^--\[=*\[");
rx!(OPEN_RUBY, r"^=begin\b");
rx!(OPEN_PY_DQ, r#"^[rRuUbB]{0,2}""""#);
rx!(OPEN_PY_SQ, r"^[rRuUbB]{0,2}'''");

fn block_openers() -> [(&'static fancy_regex::Regex, &'static str); 8] {
    [
        (OPEN_C(), "*/"),
        (OPEN_HTML(), "-->"),
        (OPEN_PS(), "#>"),
        (OPEN_HS(), "-}"),
        (OPEN_LUA(), "]]"),
        (OPEN_RUBY(), "=end"),
        (OPEN_PY_DQ(), "\"\"\""),
        (OPEN_PY_SQ(), "'''"),
    ]
}

rx!(
    DIRECTIVE,
    r"^(?:eslint|prettier-ignore|@ts-|tslint:|jshint|jscs:|global\s|istanbul\s|c8\s|v8\s|noqa|type:\s|pylint:|mypy:|pyright:|fmt:|isort:|nolint|nosec|NOSONAR|#?region\b|#?endregion\b|pragma\b|ReSharper\b|cSpell|spell-?checker|webpackChunkName|@vite-ignore|<reference\b|-\*-|vim:|shellcheck\b|nuget:|#!|@flow\b|@jsx\b|biome-ignore|deno-lint|swiftlint|rubocop:|clang-format|NOLINT|@formatter:|@generated\b|SPDX-License-Identifier|Copyright\b|\(c\)\s|©|Licensed under\b|All rights reserved|<auto-generated|codegen|@refresh|@jest-environment|@vitest-environment|language=|requires\s|#requires|using namespace)",
    "i"
);
rx!(
    TAG_PREFIX,
    r"^(?:@(?:param|arg|argument|prop|property|typeparam|template|throws|exception|callback|typedef|type|field|member|var)\b(?:\s*\{[^}]*\})?(?:\s+(?:\[[^\]]*\]|[\w$.]+))?(?:\s+-\s+|\s+|$)|@\w+(?:\s*\{[^}]*\})?(?:\s+-\s+|\s+|$)|:(?:param|type|raises|rtype|returns?|var|ivar|cvar)\b[^:]*:\s*|\\(?:param|tparam|throws|return|returns|brief|details|note)\b(?:\[[^\]]*\])?(?:\s+\w+)?\s*)"
);
rx!(MARKER_PREFIX, r"^(?:TODO|FIXME|HACK|XXX|NOTE|BUG|WARNING|WARN|IMPORTANT|REVIEW|OPTIMIZE|DEPRECATED|SAFETY|NB)(?:\([^)]*\))?:?\s+");
// Docstring conventions that documentation tools parse (Sphinx/Napoleon, NumPy); they must stay verbatim.
rx!(
    DOC_SECTION,
    r"^(?:Args|Arguments|Parameters|Params|Other Parameters|Keyword Args|Keyword Arguments|Kwargs|Returns?|Yields?|Raises|Raise|Except(?:ions)?|Warns|Warnings?|See Also|Notes?|References|Examples?|Attributes|Methods|Todo)\s*:?\s*$"
);
rx!(DOC_UNDERLINE, r"^[-=~^]{3,}\s*$");
rx!(
    DOC_ENTRY_SECTIONS,
    r"^(?:Args|Arguments|Parameters|Params|Other Parameters|Keyword Args|Keyword Arguments|Kwargs|Returns?|Yields?|Raises|Raise|Except(?:ions)?|Warns|Attributes|Methods)$"
);
// `name (type): ` (Google) and `name : ` (NumPy See Also); the whole prefix including the colon stays verbatim.
rx!(GOOGLE_ENTRY, r"^\*{0,2}[A-Za-z_][\w.]*(?:\s*\([^)]*\))?\s*:\s+");
rx!(NUMPY_ENTRY, r"^\*{0,2}[A-Za-z_]\w*(?:\s*,\s*\*{0,2}[A-Za-z_]\w*)*\s+:\s+\S.*$");
// A bare type line such as `bool`, `list[str]` or `int or None` (NumPy Returns/Yields).
rx!(TYPE_LINE, r"^[A-Za-z_][\w.]*(?:\[[^\]]*\])?(?:\s*(?:\||,|\bor\b)\s*[A-Za-z_][\w.]*(?:\[[^\]]*\])?)*$");
rx!(RST_DIRECTIVE, r"^\.\.\s+[\w-]+::\s*");

// Spans inside comment text that are code, not prose.
rx!(SPAN_DOUBLE_TICK, r"``[^`\n]+``");
rx!(SPAN_TICK, r"`[^`\n]+`");
rx!(SPAN_DOC_TAG, r"<(c|code|see|seealso|paramref|typeparamref|langword)\b[^>]*>[\s\S]*?<\/\1>");
rx!(SPAN_TAG, r"<\/?[A-Za-z][\w:.-]*(?:\s[^<>]*)?\/?>");
rx!(SPAN_JSDOC_LINK, r"\{@\w+[^}]*\}");
rx!(SPAN_RUST_LINK, r"\[`[^`\]]+`\]|\[\w+(?:::|\.)[\w.:]+\]");

rx!(
    CODE_START,
    r"^(?:import|from|export|return|if|else|elif|for|foreach|while|switch|case|var|let|const|def|class|function|func|fn|public|private|protected|static|using|namespace|package|#include|#define|try|catch|throw|await|yield|echo|cd|ls|rm|cp|mv|mkdir|sudo|npm|npx|pip|dotnet|git|docker|kubectl|az|curl|wget|param|select|insert|update|delete|create|alter|drop|print|console\.log|resource|module|output|targetScope)\b",
    "i"
);
rx!(CODE_SYMBOLS, r"[=(){}[\];$<>]|\s--?\w");
rx!(ENDS_LIKE_SENTENCE, r"[.!?:]$");
rx!(ENDS_WITH_BRACE, r"[;{}]$");
rx!(ASSIGNMENT, r#"^[\w$.[\]'"]+\s*(?:[+\-*/%|&]?=|=>|:=|<-)\s*\S"#);
rx!(PROSE_WORDS, r"\s(?:is|are|the|a|an|to|of)\s", "i");
rx!(CALL_LINE, r"^[\w$.]+\(.*\)[;,]?$");
rx!(TAG_LINE, r"^<\/?[A-Za-z][^>]*>$");
rx!(SYMBOL, r"[{}()[\];=<>$|&]");
rx!(STRONG_CODE, r"[(){}[\];=]|=>|::|->");
rx!(ENDS_SENTENCE, r"[.!?]$");
rx!(FENCE_START, r"^[ \t]*(?:`{3,}|~{3,})");
rx!(SHEBANG, r"^#!");
rx!(EXAMPLE_TAG, r"^@example\b");
rx!(ANY_TAG, r"^@\w");
rx!(DOCTEST, r"^(?:>>>|\.\.\.)(?:\s|$)");
rx!(DOCTEST_START, r"^>>>(?:\s|$)");
rx!(LITERAL_MARKER, r"::$");
rx!(BLOCK_START, r"^(?:@\w|[-*+•]\s|\d+[.)]\s|\||>|:\w+.*:|\\\w|```|~~~|<\w|\.\.\s)");
rx!(EOL, r"\r?\n");
rx!(BLANK_BEFORE, r"^[ \t]*$");
rx!(BETWEEN_LINE_COMMENTS, r"^\r?\n[ \t]*$");
rx!(C_DECO, r"^[ \t]*(?:\*(?!\/)[ \t]?)?");

fn looks_like_code(text: &str) -> bool {
    let s = jsstr::trim(text);
    if s.is_empty() {
        return false;
    }
    if CODE_START().test(s) && CODE_SYMBOLS().test(s) && !ENDS_LIKE_SENTENCE().test(s) {
        return true;
    }
    if ENDS_WITH_BRACE().test(s) {
        return true;
    }
    if ASSIGNMENT().test(s) && !PROSE_WORDS().test(s) {
        return true;
    }
    if CALL_LINE().test(s) {
        return true;
    }
    if TAG_LINE().test(s) {
        return true;
    }
    let sym = SYMBOL().all(s).len();
    sym as f64 / jsstr::u16len(s) as f64 > 0.15
}

/// Commented-out code detection. With a grammar for the language, text the grammar rejects is prose; text it
/// accepts is code when the heuristics agree or it carries a strong code signal.
pub fn is_code(lang: &str, text: &str) -> bool {
    let s = jsstr::trim(text);
    if s.is_empty() {
        return false;
    }
    let heuristic = looks_like_code(s);
    match parses_as_code(lang, s) {
        None => heuristic,
        Some(false) => false,
        Some(true) => heuristic || (STRONG_CODE().test(s) && !ENDS_SENTENCE().test(s)),
    }
}

fn col(code: &str, offset: usize) -> usize {
    column_u16(code, offset)
}

fn shape(code: &str, c: &CommentRange) -> Option<CommentShape> {
    let text = &code[c.start..c.end];
    for (re, closer) in block_openers() {
        let Some(open) = re.exec(text) else { continue };
        if !text.ends_with(closer) {
            continue;
        }
        let inner_start = c.start + open.len();
        let inner_end = c.end - closer.len();
        if inner_end < inner_start {
            return None;
        }
        let mut lines = Vec::new();
        let mut pos = inner_start;
        let c_style = closer == "*/";
        while pos <= inner_end {
            let mut nl = code[pos..].find('\n').map(|i| i + pos).unwrap_or(usize::MAX);
            if nl > inner_end {
                nl = inner_end;
            }
            let line_text = &code[pos..nl];
            let deco_len = if lines.is_empty() || !c_style { jsstr::leading_blank(line_text).len() } else { C_DECO().exec(line_text).map(|m| m.len()).unwrap_or(0) };
            let extra = jsstr::leading_blank(&line_text[deco_len..]).len();
            let body_start = pos + deco_len + extra;
            let body_end = pos + line_text.trim_end_matches([' ', '\t', '\r']).len();
            lines.push(Line { body_start, body_end: body_end.max(body_start), indent: extra, col: col(code, body_start) });
            if nl >= inner_end {
                break;
            }
            pos = nl + 1;
        }
        return Some(CommentShape { lines, closer: Some(closer) });
    }
    let marker = LINE_MARKER().exec(text)?;
    if text.contains('\n') {
        return None;
    }
    let rest = &text[marker.len()..];
    let lead = jsstr::leading_blank(rest).len();
    let body_start = c.start + marker.len() + lead;
    let body_end = c.start + text.trim_end_matches([' ', '\t', '\r']).len();
    Some(CommentShape {
        lines: vec![Line { body_start, body_end: body_end.max(body_start), indent: lead.saturating_sub(1), col: col(code, body_start) }],
        closer: None,
    })
}

fn is_own_line(code: &str, offset: usize) -> bool {
    BLANK_BEFORE().test(&code[jsstr::line_start(code, offset)..offset])
}

fn is_block_comment(t: &str) -> bool {
    block_openers().iter().any(|(re, _)| re.test(t))
}

fn standalone(t: &str) -> bool {
    SHEBANG().test(t) || DIRECTIVE().test(jsstr::trim(&LINE_MARKER().replace_all_str_first(t)))
}

/// Consecutive line comments with the same marker at the same column form one logical comment.
fn group_line_comments(code: &str, comments: &[CommentRange]) -> Vec<Vec<CommentRange>> {
    let mut groups: Vec<Vec<CommentRange>> = Vec::new();
    for c in comments {
        if let Some(prev) = groups.last().and_then(|g| g.last()).copied() {
            let between = code.get(prev.end..c.start).unwrap_or("x");
            let prev_text = &code[prev.start..prev.end];
            let cur_text = &code[c.start..c.end];
            let pm = LINE_MARKER().exec(prev_text).map(|m| m.text);
            let cm = LINE_MARKER().exec(cur_text).map(|m| m.text);
            if BETWEEN_LINE_COMMENTS().test(between)
                && pm.is_some()
                && pm == cm
                && !is_block_comment(prev_text)
                && !is_block_comment(cur_text)
                && !standalone(prev_text)
                && !standalone(cur_text)
                && col(code, prev.start) == col(code, c.start)
                && is_own_line(code, prev.start)
            {
                groups.last_mut().unwrap().push(*c);
                continue;
            }
        }
        groups.push(vec![*c]);
    }
    groups
}

trait ReplaceFirst {
    fn replace_all_str_first(&self, text: &str) -> String;
}

impl ReplaceFirst for fancy_regex::Regex {
    /// `text.replace(re, '')` for a non-global regular expression.
    fn replace_all_str_first(&self, text: &str) -> String {
        match self.exec(text) {
            Some(m) => format!("{}{}", &text[..m.start], &text[m.end..]),
            None => text.to_string(),
        }
    }
}

/// `node` is a fenced code block: `start..end` in the source, `value` its content.
pub fn process_code_block(ctx: &mut ExtractContext, start: usize, end: usize, lang: Option<&str>, value: &str) {
    let src = ctx.source;
    if !FENCE_START().test(&src[start..end]) || value.is_empty() {
        return;
    }
    let Some(lang) = lang.filter(|l| !l.is_empty()) else {
        return;
    };
    let Some(found) = find_comments(lang, value) else {
        ctx.notes.push(format!("code block \"{lang}\" left untouched (no comment parser for this language)"));
        return;
    };
    let docstrings = find_docstrings(lang, value);
    let with_docstrings = ctx.options.docstrings;
    if !docstrings.is_empty() && !with_docstrings {
        ctx.notes.push(format!("{} docstring(s) in \"{lang}\" code left untranslated (docstrings disabled)", docstrings.len()));
    }
    let docstring_starts: Vec<usize> = if with_docstrings { docstrings.iter().map(|d| d.start).collect() } else { Vec::new() };
    let mut comments = found;
    if with_docstrings {
        comments.extend(docstrings.iter().copied());
    }
    comments.sort_by_key(|c| c.start);
    if comments.is_empty() {
        return;
    }
    let Some(fence_line_end) = src[start..].find('\n').map(|i| i + start) else {
        return;
    };
    let Some(map) = LineMap::build(src, fence_line_end + 1, value) else {
        ctx.notes.push(format!("code block \"{lang}\" left untouched (could not map lines to source)"));
        return;
    };

    for group in group_line_comments(value, &comments) {
        let shapes: Vec<Option<CommentShape>> = group.iter().map(|c| shape(value, c)).collect();
        if shapes.iter().any(|s| s.is_none()) {
            continue;
        }
        let shapes: Vec<CommentShape> = shapes.into_iter().map(|s| s.unwrap()).collect();
        let lines: Vec<Line> = shapes.iter().flat_map(|s| s.lines.iter().copied()).collect();
        let closer = shapes[0].closer;
        let first_text = jsstr::trim(&value[group[0].start..lines[0].body_end.max(group[0].start)]);
        if DIRECTIVE().test(&value[lines[0].body_start..lines[0].body_end]) || SHEBANG().test(first_text) {
            continue;
        }
        let mut in_example = false;
        let docstring = docstring_starts.contains(&group[0].start);
        for para in paragraphs(value, &lines, lang, docstring) {
            let text = para.lines.iter().map(|l| &value[l.body_start..l.body_end]).collect::<Vec<_>>().join(" ");
            if EXAMPLE_TAG().test(&text) {
                in_example = true;
            } else if ANY_TAG().test(&text) {
                in_example = false;
            }
            if in_example || para.keep || DIRECTIVE().test(&text) || DOCTEST().test(&text) || is_code(lang, &text) {
                continue;
            }
            comment_segment(ctx, value, &map, &para.lines, lang, closer, docstring, para.entry);
        }
    }
}

struct Paragraph {
    lines: Vec<Line>,
    /// Structure that must stay verbatim (docstring section header, underline, NumPy entry, doctest or literal block).
    keep: bool,
    /// Inside an Args/Returns/Raises section: the entry prefix (`name (type):`) is protected.
    entry: bool,
}

fn paragraphs(value: &str, lines: &[Line], lang: &str, docstring: bool) -> Vec<Paragraph> {
    struct State<'v> {
        out: Vec<Paragraph>,
        cur: Vec<Line>,
        section: String,
        keep_cur: bool,
        literal: Option<usize>,
        docstring: bool,
        value: &'v str,
    }
    impl State<'_> {
        fn flush(&mut self, keep: bool) {
            if !self.cur.is_empty() {
                let entry = self.docstring && (DOC_ENTRY_SECTIONS().test(&self.section) || self.section == "See Also");
                let lines = std::mem::take(&mut self.cur);
                let last = *lines.last().unwrap();
                let first_col = lines[0].col;
                self.out.push(Paragraph { lines, keep: keep || self.keep_cur, entry });
                if self.docstring && !self.keep_cur && LITERAL_MARKER().test(jsstr::trim_end(&self.value[last.body_start..last.body_end])) {
                    self.literal = Some(first_col);
                }
            }
            self.cur.clear();
            self.keep_cur = false;
        }
    }
    let mut st = State { out: Vec::new(), cur: Vec::new(), section: String::new(), keep_cur: false, literal: None, docstring, value };
    let mut section_indent: isize = -1;
    let mut numpy = false;
    let mut prev_header = false;
    // Docstrings: `>>>` doctest blocks (with their output) and reST literal blocks after `::` stay verbatim.
    let mut doctest = false;
    for l in lines {
        let body = &value[l.body_start..l.body_end];
        if jsstr::trim(body).is_empty() {
            st.flush(false);
            doctest = false;
            continue;
        }
        if docstring {
            if let Some(lit) = st.literal {
                if l.col > lit {
                    if !st.keep_cur {
                        st.flush(false);
                        st.keep_cur = true;
                    }
                    st.cur.push(*l);
                    continue;
                }
                st.literal = None;
            }
            if DOCTEST_START().test(jsstr::trim(body)) {
                if !doctest {
                    st.flush(false);
                }
                st.keep_cur = true;
                doctest = true;
                st.cur.push(*l);
                continue;
            }
            if doctest {
                st.cur.push(*l);
                continue;
            }
            let header = DOC_SECTION().test(jsstr::trim(body));
            if header || DOC_UNDERLINE().test(body) {
                st.flush(false);
                if header {
                    let t = jsstr::trim(body);
                    st.section = t.strip_suffix(':').map(jsstr::trim_end).unwrap_or(t).to_string();
                    section_indent = l.col as isize;
                    numpy = false;
                } else if prev_header {
                    numpy = true;
                }
                prev_header = header;
                st.cur.push(*l);
                st.flush(true);
                continue;
            }
            prev_header = false;
            // Google style: a line back at the header's indentation ends the section (NumPy sections run to the next header).
            if !st.section.is_empty() && !numpy && (l.col as isize) <= section_indent {
                st.section.clear();
            }
            let in_entries = DOC_ENTRY_SECTIONS().test(&st.section);
            if in_entries && (NUMPY_ENTRY().test(jsstr::trim(body)) || (numpy && TYPE_LINE().test(jsstr::trim(body)))) {
                st.flush(false);
                st.cur.push(*l);
                st.flush(true);
                continue;
            }
            if (in_entries || st.section == "See Also") && GOOGLE_ENTRY().test(body) && !st.cur.is_empty() {
                st.flush(false);
            }
        }
        let code = is_code(lang, body);
        // Lines that are only a doc tag (<summary>, </remarks>) delimit paragraphs.
        let tag_only = TAG_LINE().test(jsstr::trim(body));
        let starts_block = BLOCK_START().test(body) || code || tag_only;
        if starts_block || (!st.cur.is_empty() && (l.indent as isize - st.cur[0].indent as isize).abs() >= 2) {
            st.flush(false);
        }
        st.cur.push(*l);
        if code || tag_only {
            st.flush(false);
        }
    }
    st.flush(false);
    st.out
}

#[allow(clippy::too_many_arguments)]
fn comment_segment(ctx: &mut ExtractContext, value: &str, map: &LineMap, para: &[Line], lang: &str, closer: Option<&str>, docstring: bool, entry: bool) {
    let src = ctx.source;
    let from = map.map(para[0].body_start);
    let to = map.map(para[para.len() - 1].body_end);
    let mut mb = ctx.builder();
    for (i, l) in para.iter().enumerate() {
        if i > 0 {
            mb.text(" ");
        }
        let mut body = &value[l.body_start..l.body_end];
        if i == 0 {
            let tag = TAG_PREFIX()
                .exec(body)
                .or_else(|| if docstring { RST_DIRECTIVE().exec(body).or_else(|| if entry { GOOGLE_ENTRY().exec(body) } else { None }) } else { None })
                .or_else(|| MARKER_PREFIX().exec(body));
            if let Some(tag) = tag.filter(|t| !t.is_empty()) {
                mb.placeholder(Render::literal(tag.text), tag.text, false);
                body = &body[tag.len()..];
            }
        }
        // reST: a trailing `::` introduces the literal block that follows and must survive translation.
        let literal_marker = docstring && i == para.len() - 1 && body.ends_with("::");
        if literal_marker {
            body = &body[..body.len() - 2];
        }
        mask_comment(&mut mb, body);
        if literal_marker {
            mb.placeholder(Render::literal("::"), "::", false);
        }
    }
    let mut wrap = None;
    if para.len() > 1 {
        let joiner = &src[map.map(para[0].body_end)..map.map(para[1].body_start)];
        if let Some(eol) = EOL().exec(joiner) {
            let widths = para.iter().map(|l| column_u16(src, map.map(l.body_end)));
            wrap = Some(WrapSpec {
                width: widths.max().unwrap_or(0).max(40),
                first_column: column_u16(src, from),
                prefix: joiner[eol.end..].to_string(),
                eol: eol.text.to_string(),
            });
        }
    }
    let mut forbidden: Vec<String> = closer.map(|c| vec![c.to_string()]).unwrap_or_default();
    if closer == Some("-->") {
        forbidden.push("--".into());
    }
    // Backslashes would start escape sequences inside a (non-raw) Python string.
    if docstring {
        forbidden.push("\\".into());
    }
    let note = if docstring { format!("{lang} docstring") } else { format!("{lang} source code comment") };
    let mut o = SegmentOptions::new(SegmentKind::Comment, TextContext::Comment, &src[from..to], note);
    o.wrap = wrap;
    o.forbidden = forbidden;
    if let Some(seg) = ctx.segment(mb, o) {
        ctx.replace(from, to, seg);
    }
}

fn mask_comment(mb: &mut MaskBuilder, body: &str) {
    let mut spans: Vec<(usize, usize)> = Vec::new();
    for re in [SPAN_DOUBLE_TICK(), SPAN_TICK(), SPAN_DOC_TAG(), SPAN_TAG(), SPAN_JSDOC_LINK(), SPAN_RUST_LINK()] {
        for m in re.all(body) {
            spans.push((m.start, m.end));
        }
    }
    spans.sort_by(|a, b| a.0.cmp(&b.0).then(b.1.cmp(&a.1)));
    let mut pos = 0;
    for (s, e) in spans {
        if s < pos {
            continue;
        }
        mb.source(&body[pos..s], EscapeMode::None);
        mb.placeholder(Render::literal(&body[s..e]), &body[s..e], false);
        pos = e;
    }
    mb.source(&body[pos..], EscapeMode::None);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn code_detection() {
        assert!(is_code("js", "const x = compute(a, b);"));
        assert!(!is_code("js", "Create the client for the translation service"));
        assert!(is_code("bash", "npm install --save foo"));
        assert!(!is_code("python", "Read the configuration file first"));
    }
}
